Repository cse-labs/k8s-quickstart, pull requests merged in 2021-05, with the labels that each got.

#76 merge akdc branch
  .devcontainer/devcontainer.json
  .devcontainer/post-install.sh
  Makefile
  README.md
  deploy/grafana/grafana.db
  original-content/05-Debugging-apps-in-AKS/README.md
  original-content/05-Debugging-apps-in-AKS/logapp.yaml
Labels: Documentation

#77 doc updates
  Makefile
  README.md
  deploy/fluentbit/1-account.yaml
  deploy/fluentbit/2-stdout-config.yaml
  deploy/fluentbit/3-log.yaml
  deploy/fluentbit/4-fluentbit-pod.yaml
  deploy/grafana/1-namespace.yaml
  deploy/grafana/2-datasource.yaml
  deploy/grafana/3-deployment.yaml
  deploy/grafana/4-service.yaml
  deploy/ngsa-memory/README.md
Labels: Documentation, OCW

#78 update makefile
  Makefile
  baseline.json
  benchmark.json
Labels: Bug, OCW

#79 use webv 2.0-beta1 to help test
  .devcontainer/post-install.sh
  04-Kubernetes-Kind-Cluster/README.md
  LabSeries/01-Setup-Codespaces/README.md
  LabSeries/01-Setup-Codespaces/images/DeleteCodespaceFromCodespaces.png
  LabSeries/01-Setup-Codespaces/images/DeleteCodespaceFromGitHub.png
  LabSeries/01-Setup-Codespaces/images/OpenNewCodespace.jpeg
  LabSeries/01-Setup-Codespaces/images/OpenSuspendedCodespaceFromCodespaces.png
  LabSeries/01-Setup-Codespaces/images/OpenSuspendedCodespaceFromGitHub.png
  LabSeries/01-Setup-Codespaces/images/SuspendCodespaces1.png
  LabSeries/01-Setup-Codespaces/images/SuspendCodespaces2.png
  LabSeries/02-Docker-Part-1/.profile
  LabSeries/02-Docker-Part-1/Dockerfile
  LabSeries/02-Docker-Part-1/README.md
  LabSeries/03-Docker-Part-2/README.md
  README.md
  deploy/loderunner-local/loderunner-local.yaml
Labels: InternalFeedback

#85 added workspace to repo
  04-Kubernetes-Kind-Cluster/README.md
Labels: Documentation, OCW

#88 moved instructions to asb
  04-Kubernetes-Kind-Cluster/README.md
Labels: InternalFeedback, OCW

#89 Add stop command to directions
  LabSeries/02-Docker-Part-1/README.md
Labels: Bug

#90 added directory check
  LabSeries/02-Docker-Part-1/README.md
  perfTargets.txt
Labels: Documentation, OCW

#91 updated ngsa dashboard
  deploy/dashboards/ngsa.json
  deploy/grafana/grafana.db
Labels: Bug, InternalFeedback, OCW

#92 Reset content to pre-OCW
  00-Presenter-Notes/README.md
  01-Setup-Codespaces/README.md
  01-Setup-Codespaces/images/DeleteCodespaceFromCodespaces.png
  01-Setup-Codespaces/images/DeleteCodespaceFromGitHub.png
  01-Setup-Codespaces/images/OpenNewCodespace.jpeg
  01-Setup-Codespaces/images/OpenSuspendedCodespaceFromCodespaces.png
  01-Setup-Codespaces/images/OpenSuspendedCodespaceFromGitHub.png
  01-Setup-Codespaces/images/SuspendCodespaces1.png
  01-Setup-Codespaces/images/SuspendCodespaces2.png
  02-Docker-Part-1/.profile
  02-Docker-Part-1/Dockerfile
  02-Docker-Part-1/README.md
  03-Docker-Part-2/README.md
  05-Kubernetes-Pods/README.md
  06-Kubernetes-ConfigMap-Secrets/README.md
  06-Kubernetes-ConfigMap-Secrets/secrets-description.png
  07-Kubernetes-Services/README.md
  08-Kubernetes-LodeRunner/README.md
  09-Kubernetes-Prometheus/README.md
  10-Kubernetes-Grafana/README.md
  11-Kubernetes-FluentBit/README.md
  12-Kubernetes-Deploy-From-Makefile/README.md
  13-Kubernetes-Debugging/README.md
  14-Kubernetes-Load-Test/README.md
  LabSeries/README.md
  README.md
Labels: OCW
